### PR TITLE
Add cmd param

### PR DESCRIPTION
**Pull request by petems**
Added cmd parameter …
* Defaults to dd but allows for the use of fallocate for performance.
* Added cmd option to spec file.
* Added new cmd parameter to readme

### CODE REVIEW

**Comment by petems** [comment]
@BIAndrews I'm just running some acceptance tests on this and I'm getting failures:

```
 swap_file::files { 'default':
   ensure   => present,
   cmd      => 'fallocate',
 }
```

```
Notice: /Stage[main]/Main/Swap_file::Files[default]/Exec[Attach swap file /mnt/swap.1]/returns: Setting up swapspace version 1, size = 1067004 KiB
Notice: /Stage[main]/Main/Swap_file::Files[default]/Exec[Attach swap file /mnt/swap.1]/returns: no label, UUID=1de0229e-973d-4ccb-87f0-c3b3d972fb66
Notice: /Stage[main]/Main/Swap_file::Files[default]/Exec[Attach swap file /mnt/swap.1]/returns: swapon: /mnt/swap.1: swapon failed: Invalid argument
```

Works fine with dd. Is there something else we need to do to the file with fallocate before we run swapon?

**Comment by BIAndrews** [comment]
On your system is /mnt/ XFS?

**Comment by BIAndrews** [comment]
I just manually tested it on a CentOS6 server with ext4 and it worked ok. I saw a note on the arch linux swap wiki page about XFS and fallocate problems. XFS is now the default for CentOS7 (yay!) but fallocate and XFS don't play well together (boo!)

~~~
# fallocate -l 512M /mnt/swap.test
# ls -lah /mnt/swap.test
-rw-r--r-- 1 root root 512M Nov 12 13:43 /mnt/swap.test
# mkswap /mnt/swap.test
# swapon /mnt/swap.test
# swapon -s
Filename                                Type            Size    Used    Priority
/mnt/swap.test                          file            524284  0       -1
# cat /etc/redhat-release 
CentOS release 6.7 (Final)
# mount
/dev/mapper/VolGroup-lv_root on / type ext4 (rw)
proc on /proc type proc (rw)
sysfs on /sys type sysfs (rw)
devpts on /dev/pts type devpts (rw,gid=5,mode=620)
tmpfs on /dev/shm type tmpfs (rw)
/dev/sda1 on /boot type ext4 (rw)
/dev/sdb1 on /tank type xfs (rw)
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw)
~~~

XFS FAILS:
~~~
# fallocate -l 512M /tank/swap.test
# mkswap /tank/swap.test
mkswap: /tank/swap.test: warning: don't erase bootbits sectors
        on whole disk. Use -f to force.
Setting up swapspace version 1, size = 524284 KiB
no label, UUID=5702bbae-b712-4f24-8066-1e35c7b8ed45
# echo $?
0
# swapon /tank/swap.test
swapon: /tank/swap.test: swapon failed: Invalid argument
# mount | grep tank
/dev/sdb1 on /tank type xfs (rw)
~~~

**Comment by petems** [comment]
@BIAndrews Ah, yes I'm running this test on a Centos 7 vagrant machine. Good spot!

Hmm, we should probably put a warning/fail if filesystem is XFS when picking fallocate. Let me whip something up...

**Comment by petems** [comment]
Weird it's marked as "not a bug" here: https://bugzilla.redhat.com/show_bug.cgi?id=1129205

I'm wondering whether to do a bunch of checking kernel and filesystem stuff, or just add a puppet warning for the fallocate command and allow buyer beware...

**Pull request merged**
